### ISSUE TITLE
cannot find "circFL_example/sRG/../RG/ExonSdict.npy" 

### ISSUE THREAD

**Issue by algaebrown** [yangence/circfull#10]
```
Traceback (most recent call last):
  File "/home/hsher/miniconda3/envs/circfull/bin/circfull", line 33, in <module>
    sys.exit(load_entry_point('circfull==0.1.0', 'console_scripts', 'circfull')())
  File "/home/hsher/miniconda3/envs/circfull/lib/python3.7/site-packages/circfull-0.1.0-py3.7.egg/circfull/circFL_main.py", line 50, in main
  File "/home/hsher/miniconda3/envs/circfull/lib/python3.7/site-packages/circfull-0.1.0-py3.7.egg/circfull/sRG.py", line 112, in sRG
  File "/home/hsher/miniconda3/envs/circfull/lib/python3.7/site-packages/circfull-0.1.0-py3.7.egg/circfull/RG_filterBS.py", line 290, in filterBS
  File "/home/hsher/miniconda3/envs/circfull/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'circFL_example/sRG/../RG/ExonSdict.npy'
```
I was running using the examples you provided. Where is file from? `circFL_example/sRG/../RG/ExonSdict.npy`
and is the file strand-specific? Can I just generate this at the beginning using the GTF???

Thanks

**Comment by colinliuzelin** [comment]
Thank you for your question. It seems you are running "circfull strand" which is dependend on the result of "circfull  RG". You can try to find the 'ExonSdict.npy' at your 'circFL_example/RG/' directory.
You can copy 'ExonSdict.npy' 'ExonSdict_fsj.npy'  'ExonEdict.npy' 'ExonEdict_fsj.npy' into the folder of your GTF file. circfull will use it instead of generating it every time. So far, there is no commond to just generate these files. And these files are stranded.
Zelin

**Comment by algaebrown** [comment]
Thank you! I was able to find such file after i rerun in a clean directory
