### ISSUE TITLE
AssertionError in Analyze SAM file: explainFL

### ISSUE THREAD

**Issue by aerusakovich** [yangence/circfull#15]
Hello!

Was trying to use circFL and in RG step encountered error.

Here is log:
```

Usage: circfull <command> [options]
Command:
    RG             Reference guide detection
    DNSC           De novo self-correction to get consensus sequence
    cRG            Use RG algorithem with sequences corrected by DNSC
    strand         Identify the strand origion of circFL-seq reads
    sRG            RG algorithem with stranded circFL-seq reads.
    mRG            Merge circFL results from RG and cRG/sRG.
    anno           Annotate full-length circRNA.
    geneExp        Quantify gene expression to evaluate linear RNA residual
    var            Calling variants in circRNA.
    partial        Count partial circRNA.

Running circFL on data_ciri-long-rep_1
Reference guide detection
#### 2024-06-11 12:00:18 #### 
Check fastq file
#### 2024-06-11 12:00:18 #### 
Check anno file
#### 2024-06-11 12:00:18 #### 
Check genome file
#### 2024-06-11 12:00:18 #### 
Align fastq to reference genome: alignFastq
#### 2024-06-11 12:33:20 #### 
Transform SAM to BAM: sam2bam
#### 2024-06-11 12:33:20 #### 
Analyze SAM file: explainFL
Traceback (most recent call last):
  File "/home/genouest/cnrs_umr6290/aerusakovich/.conda/envs/circFL_3.7/bin/circfull", line 8, in <module>
    sys.exit(main())
  File "/home/genouest/cnrs_umr6290/aerusakovich/.conda/envs/circFL_3.7/lib/python3.7/site-packages/circfull/circFL_main.py", line 38, in main
    RG.RG(docopt(RG.__doc__, version=__version__))
  File "/home/genouest/cnrs_umr6290/aerusakovich/.conda/envs/circFL_3.7/lib/python3.7/site-packages/circfull/RG.py", line 95, in RG
    explainFL(genome,RG_outPrefix,sam)
  File "/home/genouest/cnrs_umr6290/aerusakovich/.conda/envs/circFL_3.7/lib/python3.7/site-packages/circfull/RG_explainFL.py", line 48, in explainFL
    leftSeq=genome.sequence({'chr': readInfo[1], 'start':readInfo[2]-1, 'stop':readInfo[2]}).upper()
  File "/home/genouest/cnrs_umr6290/aerusakovich/.conda/envs/circFL_3.7/lib/python3.7/site-packages/pyfasta/fasta.py", line 197, in sequence
    assert 'chr' in f and f['chr'] in self, (f, f['chr'], list(self.keys()))
AssertionError: ({'chr': 'chr16', 'start': 94397256, 'stop': 94397257}, 'chr16', ['chr1 1', 'chr2 2', 'chr3 3', 'chr4 4', 'chr5 5', 'chr6 6', 'chr7 7', 'chr8 8', 'chr9 9', 'chr10 10', 'chr11 11', 'chr12 12', 'chr13 13', 'chr14 14', 'chr15 15', 'chr16 16', 'chr17 17', 'chr18 18', 'chr19 19', 'chrX X', 'chrY Y', 'chrM MT', 'GL456210.1 GL456210.1', 'GL456211.1 GL456211.1', 'GL456212.1 GL456212.1', 'GL456213.1 GL456213.1', 'GL456216.1 GL456216.1', 'GL456219.1 GL456219.1', 'GL456221.1 GL456221.1', 'GL456233.1 GL456233.1', 'GL456239.1 GL456239.1', 'GL456350.1 GL456350.1', 'GL456354.1 GL456354.1', 'GL456359.1 GL456359.1', 'GL456360.1 GL456360.1', 'GL456366.1 GL456366.1', 'GL456367.1 GL456367.1', 'GL456368.1 GL456368.1', 'GL456370.1 GL456370.1', 'GL456372.1 GL456372.1', 'GL456378.1 GL456378.1', 'GL456379.1 GL456379.1', 'GL456381.1 GL456381.1', 'GL456382.1 GL456382.1', 'GL456383.1 GL456383.1', 'GL456385.1 GL456385.1', 'GL456387.1 GL456387.1', 'GL456389.1 GL456389.1', 'GL456390.1 GL456390.1', 'GL456392.1 GL456392.1', 'GL456393.1 GL456393.1', 'GL456394.1 GL456394.1', 'GL456396.1 GL456396.1', 'JH584292.1 JH584292.1', 'JH584293.1 JH584293.1', 'JH584294.1 JH584294.1', 'JH584295.1 JH584295.1', 'JH584296.1 JH584296.1', 'JH584297.1 JH584297.1', 'JH584298.1 JH584298.1', 'JH584299.1 JH584299.1', 'JH584300.1 JH584300.1', 'JH584301.1 JH584301.1', 'JH584302.1 JH584302.1', 'JH584303.1 JH584303.1', 'JH584304.1 JH584304.1', 'KQ030490.1 MG117_PATCH', 'KB469738.3 MG132_PATCH', 'JH792830.1 MG153_PATCH', 'KK082442.1 MG184_PATCH', 'KQ030495.1 MG3231_PATCH', 'KQ030485.1 MG3561_PATCH', 'KQ030486.1 MG3562_PATCH', 'KQ030487.1 MG3609_PATCH', 'KB469739.1 MG3829_PATCH', 'KB469741.1 MG3833_PATCH', 'JH792829.1 MG3835_PATCH', 'JH792826.1 MG4136_PATCH', 'JH792828.1 MG4151_PATCH', 'KB469740.1 MG4180_PATCH', 'JH792832.1 MG4209_PATCH', 'JH792833.1 MG4211_PATCH', 'JH792827.1 MG4212_PATCH', 'JH792834.1 MG4213_PATCH', 'JH792831.1 MG4214_PATCH', 'KB469742.1 MG4222_MG3908_PATCH', 'KQ030484.1 MG4248_PATCH', 'KQ030494.1 MG4249_PATCH', 'KQ030496.1 MG4254_PATCH', 'KQ030497.1 MG4255_PATCH', 'KQ030492.1 MG4259_PATCH', 'KQ030493.1 MG4261_PATCH', 'KQ030491.1 MG4264_PATCH', 'KQ030488.1 MG4265_PATCH', 'KQ030489.1 MG4266_PATCH', 'KK082441.1 MMCHR1_CHORI29_IDD5_1'])
Finished
```

The script:
```
# Activate env
source /local/env/envpython-3.7.1.sh
conda activate circFL_3.7
circfull -h

#Paths
data_name="data_ciri-long-rep_1"
prog_name="circFL"
ref_name="GRCm38.p4"
gene_anno="M10"
output_dir="/home/genouest/cnrs_umr6290/aerusakovich/benchmark/results/$prog_name/$data_name/$ref_name/$gene_anno"
reads_path="/home/genouest/cnrs_umr6290/aerusakovich/benchmark/data/ciri-long/rep1/CRR194180.fq"
ref_path="/home/genouest/cnrs_umr6290/aerusakovich/benchmark/data/ciri-long/files/m38/GRCm38.p4.genome.fa"
gene_anno_path="/home/genouest/cnrs_umr6290/aerusakovich/benchmark/data/ciri-long/files/m38/gencode.vM10.sorted.annotation.gtf.gz"


#Parameters
THREADS=8


mkdir -p "$output_dir"
cd /groups/dog/anastasia/progs/circFL
echo "Running circFL on $data_name"
    
echo "Reference guide detection"
circfull RG -f "$reads_path" -g "$ref_path" -a "$gene_anno_path" -t $THREADS -o "$output_dir"

```

Could you suggest how to fix it?

**Comment by aerusakovich** [comment]
Figured it out, had to change chromosome names in ref
