### ISSUE TITLE
RG_fusion1CombinFL.py IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by gnilihzeux** [yangence/circfull#3]
Dear author,
    The details is as follows
```
Construct fusion FL-circRNA: fusion1ConstructFL
#### 2021-12-15 17:26:11 ####
Adjust fusion FL-circRNA: fusion1AdjFL
#### 2021-12-15 17:33:21 ####
Annotate fusion FL-circRNA: fusion1CombinFL
Traceback (most recent call last):
  File "/home/jinwen/miniconda3/envs/nanopore/bin/circfull", line 8, in <module>
    sys.exit(main())
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull/circFL_main.py", line 37, in main
    RG.RG(docopt(RG.__doc__, version=__version__))
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull/RG.py", line 127, in RG
    fusion1CombinFL([genome,fus_outPrefix,anno])
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull/RG_fusion1CombinFL.py", line 182, in fusion1CombinFL
    consFL_all_pass['strand_second']=strandList.iloc[:,1].to_list()
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1443, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 702, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1352, in _validate_key
    self._validate_integer(key, axis)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

  What should I do?

  BTW, my OS env are list as
```
# OS
CentOS Linux release 7.6.1810 (Core)
conda 4.10.1
Python 3.6.13 :: Anaconda, Inc.
# genome
GENCODE GRCh37 p13
# install method
pip install circfull
```

  Thanks for your time.

**Comment by koosle** [comment]
I have the same problem.

**Comment by colinliuzelin** [comment]
Thank you for your feedback and continually interest in circfull. I have fixed the bug. You can install the newest version 0.0.7 after uninstall the old version.

**Comment by gnilihzeux** [comment]
Wow, you're so efficient. The problem has been solved.

Thanks a lot.
