### ISSUE TITLE
ValueError: could not create iterator for region 'JH159134.2:1007307-1007307'

### ISSUE THREAD

**Issue by JinwenBioinfo** [yangence/circfull#4]
Dear author,
  I had understand what happened behind the error, but couldn't solve it. Could you please help me ?
  The error came out while runing one of my samples, details as :
```
#### 2021-12-17 00:04:04 ####
Annotate fusion FL-circRNA: fusion1CombinFL
Traceback (most recent call last):
  File "/home/jinwen/miniconda3/envs/nanopore/bin/circfull", line 33, in <module>
    sys.exit(load_entry_point('circfull==0.0.7', 'console_scripts', 'circfull')())
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.7-py3.6.egg/circfull/circFL_main.py", line 37, in main
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.7-py3.6.egg/circfull/RG.py", line 127, in RG
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.7-py3.6.egg/circfull/RG_fusion1CombinFL.py", line 192, in fusion1CombinFL
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.7-py3.6.egg/circfull/RG_fusion1CombinFL.py", line 73, in getGene
  File "pysam/libctabix.pyx", line 508, in pysam.libctabix.TabixFile.fetch
ValueError: could not create iterator for region 'JH159134.2:1007307-1007307'
```
After browsering `RG_fusion1CombinFL.py`, 
```
# line73, getGene
for gtf in tabixfile.fetch(tmp['chr'], tmp['start']-1, tmp['start'],parser=pysam.asGTF()):
# line 192, fusion1CombinFL
 geneNameList2.append(getGene(tmp['chr_second'],tmp['start_second'],tmp['end_second'],tmp['strand_second']))

# line 143, 144
consFL_all=pd.concat([BSdf[['circID']],consFL_1[['chr','start','end','len','exonNum','exon_start','exon_end','exon_leftSeq','exon_rightSeq']],explainF['strand'],                      consFL_2[['chr','start','end','len','exonNum','exon_start','exon_end','exon_leftSeq','exon_rightSeq']],BSdf[['strand']]],axis=1).copy()
# line 133
BSdf=pd.read_csv(outPrefix+'BS_Fusion1_adj.txt',sep='\t')
# line 127
consFL_2=pd.read_csv(outPrefix+'constructFL_Fusion1_adj_2.txt',sep='\t')
```

I located the file information :

```
$grep JH159134 BS_Fusion1_adj.txt
98e82765-0d86-4ebe-945b-624014f77e66    chr10   JH159134.2      95089591        1007298 CT      AG      1007443 9ue      chr10|JH159134.2|95089591|1007298|1007443|95089421
dd21f59f-f63a-49bd-ae86-a99bef4028f6    chr10   JH159134.2      95089591        1007307 CT      AG      1007443 9ue      chr10|JH159134.2|95089591|1007307|1007443|95089421

$grep JH159134 BS_Fusion1_adj.txt
98e82765-0d86-4ebe-945b-624014f77e66    chr10   JH159134.2      95089591        1007298 CT      AG      1007443 9ue      chr10|JH159134.2|95089591|1007298|1007443|95089421
dd21f59f-f63a-49bd-ae86-a99bef4028f6    chr10   JH159134.2      95089591        1007307 CT      AG      1007443 9ue      chr10|JH159134.2|95089591|1007307|1007443|95089421
```

The region should be ` tmp['start']-1, tmp['start']`, but what happened to the result  `JH159134.2:1007307-1007307` ?

Hope for your help.

**Comment by colinliuzelin** [comment]
Thank you for your feedback. I have fixed the bug, which caused by the chr name 'JH159134.2'. You can install the newest version 0.0.8.
Some details: Some supplementary contigs in genome file (such as, GRCH37 downloaded from NCBI) have not matched annotations in GTF file.  Although I fix the bug in your issue, some similar problems may also happen. Thus, I suggest that you remove those supplementary contigs in your genome file. I will have a thorough check for potential errors in a few days.

**Comment by JinwenBioinfo** [comment]
Oh, that's great. Wish your next version.
