### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by koosle** [yangence/circfull#7]
Dear author,
    Hi! 
    When I run the circfull, there was a bug about that "IndexError: single positional indexer is out-of-bounds".
    The version of circfull is 0.0.8. Some samples could be all done, but others has the above bug.
    Could you give me some suggestions? Thanks a lot!

**Comment by koosle** [comment]
`Filter BS: filterBS
#### 2022-06-29 10:36:09
Construct FL-circRNA: constructFL
#### 2022-06-29 10:37:45
Adjust FL-circRNA: adjFL
#### 2022-06-29 10:47:06
Adjust mistaken circRNA: circSeq
#### 2022-06-29 10:47:29
Annotate circRNA: annotateNormal
#### 2022-06-29 10:47:44
Analyze fusion circRNA: fusionFq
#### 2022-06-29 10:47:49
Re-alignment to pseudo reference: detectBS_fusion1
#### 2022-06-29 10:48:11
Filter fusion BS: filterBS_fusion1
#### 2022-06-29 10:52:46
Construct fusion FL-circRNA: fusion1ConstructFL
#### 2022-06-29 10:55:09
Adjust fusion FL-circRNA: fusion1AdjFL
#### 2022-06-29 11:05:03 ####
Annotate fusion FL-circRNA: fusion1CombinFL
Traceback (most recent call last):
  File "/home/jinwen/miniconda3/envs/nanopore/bin/circfull", line 33, in <module>
    sys.exit(load_entry_point('circfull==0.0.8', 'console_scripts', 'circfull')())
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/circFL_main.py", line 37, in main
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/RG.py", line 127, in RG
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/RG_fusion1CombinFL.py", line 182, in fusion1CombinFL
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1443, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 702, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1352, in _validate_key
    self._validate_integer(key, axis)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds`

**Comment by koosle** [comment]
The bug as the list:

`Filter BS: filterBS
#### 2022-06-29 10:36:09
Construct FL-circRNA: constructFL
#### 2022-06-29 10:37:45
Adjust FL-circRNA: adjFL
#### 2022-06-29 10:47:06
Adjust mistaken circRNA: circSeq
#### 2022-06-29 10:47:29
Annotate circRNA: annotateNormal
#### 2022-06-29 10:47:44
Analyze fusion circRNA: fusionFq
#### 2022-06-29 10:47:49
Re-alignment to pseudo reference: detectBS_fusion1
#### 2022-06-29 10:48:11
Filter fusion BS: filterBS_fusion1
#### 2022-06-29 10:52:46
Construct fusion FL-circRNA: fusion1ConstructFL
#### 2022-06-29 10:55:09
Adjust fusion FL-circRNA: fusion1AdjFL
#### 2022-06-29 11:05:03 ####
Annotate fusion FL-circRNA: fusion1CombinFL
Traceback (most recent call last):
  File "/home/jinwen/miniconda3/envs/nanopore/bin/circfull", line 33, in <module>
    sys.exit(load_entry_point('circfull==0.0.8', 'console_scripts', 'circfull')())
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/circFL_main.py", line 37, in main
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/RG.py", line 127, in RG
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/RG_fusion1CombinFL.py", line 182, in fusion1CombinFL
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1443, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 702, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1352, in _validate_key
    self._validate_integer(key, axis)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds`

**Comment by colinliuzelin** [comment]
Hi koosle! Thank you for your feedback. I have some thoughts about this bug but need your file to have a test. Could you send me your output files in fusion directory?
Thanks

**Comment by koosle** [comment]
> 



> Hi koosle! Thank you for your feedback. I have some thoughts about this bug but need your file to test it. Could you send me your output files in fusion directory? Thanks

All files of “fusion” folder?

**Comment by colinliuzelin** [comment]
A compressed package of fusion directory. I think its size is small.

**Comment by koosle** [comment]
> A compressed package of fusion directory. I think its size is small.

The file directory is (https://github.com/koosle/tmp) ,  you can download it.

**Comment by colinliuzelin** [comment]
Hi koosle! I have checked your file. It seems some of reads were mapped on reference patches, such as GL582976.1, GL949752.1. I suggest you to only keep chromosomes starting with 'chr' in your reference geome and re-run circfull.

**Comment by koosle** [comment]
Thanks for your suggestion. I had tried your method again, but it was still left the same problem. 
Is it possible that these samples do not have fusion genes?

**Comment by colinliuzelin** [comment]
I agree it is possible that these samples do not have fusion genes. However, circfull will pass through this part if there is no fusion circRNA. Could you send me the compressed package of fusion directory without reference patches? I want to figure out this problem. Thank you!

**Comment by koosle** [comment]
The file directory is (https://github.com/koosle/temp2) .
Thank you again!

**Comment by koosle** [comment]
Thanks for your job!
I have changed the circfull script with your files and tried again, but the same bug still existed.

**Comment by colinliuzelin** [comment]
Thank you for your feedback. Could you provide me the read sequence of 'cd2fc60b-591f-488e-a821-dd66c36e3893', your genome version and annotation file? The read sequence may provide some information.

**Comment by gnilihzeux** [comment]
@colinliuzelin Hi, have you solve this? I suffered the same problem.

**Comment by colinliuzelin** [comment]
Sorry for the late response. Can you provide your reference genome and GTF annotation file? And the error information of this time. Thank you!

**Comment by gnilihzeux** [comment]
The genome and gtf are from `GENCODE GRCh37.p13`.

The error information :
```
Annotate fusion FL-circRNA: fusion2CombinFL
Traceback (most recent call last):
  File "/home/jinwen/miniconda3/envs/nanopore/bin/circfull", line 33, in <module>
    sys.exit(load_entry_point('circfull==0.0.8', 'console_scripts', 'circfull')())
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/circFL_main.py", line 37, in main
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/RG.py", line 153, in RG
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/RG_fusion2CombinFL.py", line 182, in fusion2CombinFL
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 873, in __getitem__
    return self._getitem_tuple(key)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1443, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 702, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1352, in _validate_key
    self._validate_integer(key, axis)
  File "/home/jinwen/miniconda3/envs/nanopore/lib/python3.6/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by colinliuzelin** [comment]
> The genome and gtf are from `GENCODE GRCh37.p13` and they are all about 'Chr' information without paches.
> 
> The error information :
> 
> ```
> Annotate fusion FL-circRNA: fusion2CombinFL
> Traceback (most recent call last):
>   File "/home/gnilihzeux/miniconda3/envs/nano/bin/circfull", line 33, in <module>
>     sys.exit(load_entry_point('circfull==0.0.8', 'console_scripts', 'circfull')())
>   File "/home/gnilihzeux/miniconda3/envs/nano/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/circFL_main.py", line 37, in main
>   File "/home/gnilihzeux/miniconda3/envs/nano/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/RG.py", line 153, in RG
>   File "/home/gnilihzeux/miniconda3/envs/nano/lib/python3.6/site-packages/circfull-0.0.8-py3.6.egg/circfull/RG_fusion2CombinFL.py", line 182, in fusion2CombinFL
>   File "/home/gnilihzeux/miniconda3/envs/nano/lib/python3.6/site-packages/pandas/core/indexing.py", line 873, in __getitem__
>     return self._getitem_tuple(key)
>   File "/home/gnilihzeux/miniconda3/envs/nano/lib/python3.6/site-packages/pandas/core/indexing.py", line 1443, in _getitem_tuple
>     self._has_valid_tuple(tup)
>   File "/home/gnilihzeux/miniconda3/envs/nano/lib/python3.6/site-packages/pandas/core/indexing.py", line 702, in _has_valid_tuple
>     self._validate_key(k, i)
>   File "/home/gnilihzeux/miniconda3/envs/nano/lib/python3.6/site-packages/pandas/core/indexing.py", line 1352, in _validate_key
>     self._validate_integer(key, axis)
>   File "/home/gnilihzeux/miniconda3/envs/nano/lib/python3.6/site-packages/pandas/core/indexing.py", line 1437, in _validate_integer
>     raise IndexError("single positional indexer is out-of-bounds")
> IndexError: single positional indexer is out-of-bounds
> ```

Hi! Have you tried these new scripts in https://github.com/yangence/circfull/tree/develop/script/circfull. You can change your circfull script with the files. If you still have the bug, please tell me the error information. Thank you!

**Comment by gnilihzeux** [comment]
Great, it works. I changed the `circfull scripts` and re-install them.
Thanks a million.
