### ISSUE TITLE
De-novo consensus calling module

### ISSUE THREAD

**Issue by bredward** [yangence/circfull#8]
Hi there,

I am running into another issue with the DNSC module and subsequent downstream modules. I've pasted the error below:

(circfull.new) bredward@PMB-30S5B03:~$ circfull DNSC -f $cleanFq -t $thread -o $out
#### 2022-07-15 11:37:18 ####
Check fastq file
#### 2022-07-15 11:37:18 ####
Transform fastq to fasta: fastq2fa
#### 2022-07-15 11:37:22 ####
Detect consensue sequence: tideHunter
[abpoa_gen_cons] No enough sequences to perform msa.

[abpoa_gen_cons] No enough sequences to perform msa.

#### 2022-07-15 11:37:24 ####
Filter consensue sequence: getNovo
Traceback (most recent call last):
  File "/home/bredward/miniconda3/envs/circfull.new/bin/circfull", line 33, in <module>
    sys.exit(load_entry_point('circfull==0.0.8', 'console_scripts', 'circfull')())
  File "/home/bredward/miniconda3/envs/circfull.new/lib/python3.9/site-packages/circfull-0.0.8-py3.9.egg/circfull/circFL_main.py", line 40, in main
  File "/home/bredward/miniconda3/envs/circfull.new/lib/python3.9/site-packages/circfull-0.0.8-py3.9.egg/circfull/DNSC.py", line 71, in DNSC
  File "/home/bredward/miniconda3/envs/circfull.new/lib/python3.9/site-packages/circfull-0.0.8-py3.9.egg/circfull/DNSC_getNovo.py", line 32, in getNovo
  File "/home/bredward/miniconda3/envs/circfull.new/lib/python3.9/site-packages/pandas/core/series.py", line 955, in __getitem__
    return self._values[key]
IndexError: index 0 is out of bounds for axis 0 with size 0

If I'm not mistaken, I believe this came about because there is too little data to determine a consensus because I noticed that cRG throws an error as well (pasted below):

#### 2022-07-15 11:42:21 ####
Check DNSC directory
ERROR: make sure file of TideHunter_Pass.tab in /mnt/c/Users/bredward/Documents/circFL_run2/pass/circfull/

I would still like to proceed to the merge & annotation steps if possible however it seems that the merge process will not run without a BAM alignment file in the RG directory. I can see from the error that the file that is missing is the same filename as the SAM alignment in the RG directory though... see below:

######### ERROR RUNNinG cRG module ######
(circfull.new) bredward@PMB-30S5B03:~$ circfull mRG -t $thread -g $genome -f $cleanFq -r $out -c $out -s $out -o  $out
#### 2022-07-15 11:50:49 ####
Check fastq file
#### 2022-07-15 11:50:49 ####
Check genome file
#### 2022-07-15 11:50:49 ####
Check RG directory
#### 2022-07-15 11:50:49 ####
Check cRG directory
#### 2022-07-15 11:50:49 ####
Warning: make sure file of circFL_Normal.txt in /mnt/c/Users/bredward/Documents/circFL_run2/pass/circfull/ or /mnt/c/Users/bredward/Documents/circFL_run2/pass/circfull/cRG/
#### 2022-07-15 11:50:49 ####
Check sRG directory
#### 2022-07-15 11:50:49 ####
Merge results from RG and sRG: merge
#### 2022-07-15 11:50:49 ####
Transform SAM to BAM: sam2bam
#### 2022-07-15 11:50:51 ####
Filter circFL results: filterOut
[E::hts_open_format] Failed to open file "/mnt/c/Users/bredward/Documents/circFL_run2/pass/circfull/RG/test.minimap2.bam" : No such file or directory
Traceback (most recent call last):
  File "/home/bredward/miniconda3/envs/circfull.new/bin/circfull", line 33, in <module>
    sys.exit(load_entry_point('circfull==0.0.8', 'console_scripts', 'circfull')())
  File "/home/bredward/miniconda3/envs/circfull.new/lib/python3.9/site-packages/circfull-0.0.8-py3.9.egg/circfull/circFL_main.py", line 46, in main
  File "/home/bredward/miniconda3/envs/circfull.new/lib/python3.9/site-packages/circfull-0.0.8-py3.9.egg/circfull/mRG.py", line 108, in mRG
  File "/home/bredward/miniconda3/envs/circfull.new/lib/python3.9/site-packages/circfull-0.0.8-py3.9.egg/circfull/RG_filterOut.py", line 218, in filterOut
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 950, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `/mnt/c/Users/bredward/Documents/circFL_run2/pass/circfull/RG/test.minimap2.bam`: No such file or directory

I realize that this file is missing for a reason but for the sake of doing the downstream annotation, would it be appropriate to simply convert this to BAM and try rerunning? Or would doing so negatively affect the results in any way? If you could suggest a way to proceed with summarizing the results in a way that incorporates the results from the RG, strand, and sRG without performing any de-novo correction or consensus calling? 

Thank you, I really appreciate your help with this!

Bri

**Comment by colinliuzelin** [comment]
Thank you for your feedback. I am not sure about the bug. But it seems happens in the **Detect consensue sequence: tideHunter** step. With the improvement of nanopore raw read accuracy, It could be no big differences with or without the self consensus correction step. In the mRG step, the parameter **-c** is optional, means you can just summarize the results from RG and sRG.
